services:
  hub-home-agn:
    image: ghcr.io/denysskobalo/hub-home-agn:latest
    container_name: hub-home-agn
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - /srv/projects/dss-hub/data:/app/data
      - /proc:/host/proc:ro
    deploy:
      resources:
        limits:
          memory: 64M
    logging:
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "3"
    networks: 
      dss-hub-net:
        aliases:
          - hub-home-agn

  hub-ana-api:
    image: ghcr.io/denysskobalo/hub-ana-api:latest
    container_name: hub-ana-api
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - /srv/projects/dss-hub/data:/app/data
    deploy:
      resources:
        limits:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      dss-hub-net:
        aliases:
          - hub-ana-api

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: hub-sec-tnl
    restart: unless-stopped
    command: tunnel run
    env_file: ../.env 
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - dss-hub-net

networks:
  dss-hub-net:
    driver: bridge
